export const GET_ALL_POSTS="GET_ALL_POSTS"
export const GET_ALL_DEVICEREDUCER="GET_ALL_DEVICEREDUCER"
export const GET_ALL_SADMINREDUCER="GET_ALL_SADMINREDUCER"
export const GET_ALL_DOCTORREDUCER="GET_ALL_DOCTORREDUCER"

